Repository linz/nz-aerial-survey-indexes, pull requests merged in 2020-06, with the labels that each got.

#60 test: manual tests
  tests/manual_test/10k_precise_points.sql
  tests/manual_test/1k_precise_points.sql
  tests/manual_test/50k_precise_points.sql
  tests/manual_test/5k_precise_points.sql
Labels: pr: changes approved, pr: no changelog, pr: not closing issue

#61 ci: switch from Travis CI to GitHub Actions
  .github/workflows/build.yml
  .travis.yml
  CHANGELOG.rst
  README.rst
Labels: pr: review requested

#63 chore: rename repo from nz-imagery-surveys to nz-aerial-survey-indexes
  README.rst
Labels: pr: changes approved, pr: no changelog, pr: no reviewer
